### ISSUE TITLE
First working prototype

### ISSUE THREAD

**Issue by bertspaan** [histograph/io#6]
- [x] #2 Input file format
- [x] #3 REST API for POSTing NDJSON files
- [x] #4 Compute diffs, push to queue
